default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: course_enrollment_development

test:
  <<: *default
  database: course_enrollment_test

#production:
#  <<: *default
#  database: course_enrollment_production
#  username: course_enrollment
#  password: <%= ENV['MYSQLTEST_DATABASE_PASSWORD'] %>